# Generated by Django 4.2.3 on 2023-07-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_hashtags_delete_follow_post_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(null=True, related_name='post', to='social.hashtags'),
        ),
    ]
